CREATE TABLE "customer" (
    id INTEGER PRIMARY KEY,
    fName TEXT NOT NULL,
    lName TEXT NOT NULL,
    dob DATE NOT NULL,
    memberId TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    phone TEXT,
    email TEXT,
    appealsId TEXT,
    isOnline NUMERIC,
    noticeDate DATETIME,
    repFName TEXT,
    repLName TEXT,
    repAddress TEXT,
    repCity TEXT,
    repState TEXT,
    repZip TEXT,
    noticeNumber TEXT,
    dateEntered DATETIME,
    dateReceived DATETIME,
    income NUMERIC,
    residency NUMERIC,
    otherInsurance NUMERIC,
    lawfulPresence NUMERIC,
    familySize NUMERIC,
    incarceration NUMERIC,
    
);

CREATE TABLE "outreach" (
    id INTEGER PRIMARY KEY,
    customerId INTEGER NOT NULL,
    notes TEXT,
    contactMethod TEXT,
    contactMade NUMERIC,
    outcome TEXT,
    timeSpent INTEGER,
    createdAt DATETIME,
    updatedAt DATETIME,
    FOREIGN KEY(customerId) REFERENCES customer(id)
);